<a href="https://colab.research.google.com/github/vishwanathbeena/appliedai_practice/blob/main/1_Python_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists
def matrix_mul(A, B):
    # write your code
    if (not isinstance(A,list) and  not isinstance(B,list)):
       return 'Please pass two matrices as lists'
    rows_of_A = len(A)       
    cols_of_A = len(A[0])
    rows_of_B = len(B)
    cols_of_B = len(B[0])
    if cols_of_A != rows_of_B:
      return 'A*B is not possible'
    result_matrix = []
    for i in range(rows_of_A):
      row_list = []
      for j in range(cols_of_B):
        temp_val = 0
        for k in range(rows_of_B):
          temp_val = temp_val + A[i][k] * B[k][j]
        row_list.append(temp_val)
      result_matrix.append(row_list)
    return result_matrix       

A = [[1,2],[3,4],[4,5]]
B = [[1,2,3,4,5],[5,6,7,8,9]]
result = matrix_mul(A, B)
print(result)

[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51], [29, 38, 47, 56, 65]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [70]:
from random import uniform
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability propotional to its magnitude
    d_dash = [float(i)/sum(A) for i in A]
    d_tilda = [0]*len(d_dash)
    for i in range(len(d_dash)):
      d_tilda[i] = d_dash[i] + d_tilda[i - 1]
    random_var = uniform(0,1)
    final_val = None
    for i in range(len(d_tilda)):
      if random_var <= d_tilda[i]:
         final_val = A[i]
         break;
    return final_val

def sampling_based_on_magnitued(A):
    final_dict = {}
    for i in range(1,100):
        number = pick_a_number_from_list(A)
        if number in final_dict:
            final_dict[number] += 1
        else:
            final_dict[number] = 1
    return final_dict
A = [0,5,27,6,13,28,100,45,10,79]
sampling_based_on_magnitued(A)

{5: 1, 6: 2, 10: 4, 13: 4, 27: 11, 28: 6, 45: 18, 79: 23, 100: 30}

<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [ ]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program
def replace_digits(str_val):
    # write your code
    # 
    remove_nondigit = re.sub('[^0-9]','',str_val)
    replace_digit = re.sub('[0-9]','#',remove_nondigit)
    return(replace_digit) # modified string which is after replacing the # with digits
str_val = '#2a$#b%c%561#'
print(replace_digits(str_val))

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
def display_dash_board(students, Marks):
    zipped_list = zip(Marks,Students)
    sorted_list = sorted(zipped_list)
    # write code for computing top top 5 students
    top_5_students = sorted_list[:len(sorted_list)-6:-1]
    # write code for computing top least 5 students
    least_5_students = sorted_list[0:5]
    # write code for computing top least 5 students
    students_within_25_and_75 = sorted_list[int(len(sorted_list)/4):int((len(sorted_list)*(3/4))+1)]    
    return top_5_students, least_5_students, students_within_25_and_75

Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10','student11'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80,93]
zipped_list = zip(Marks,Students)
sorted_list = sorted(zipped_list)

top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(Students, Marks)
print(top_5_students)
print(least_5_students)
print(students_within_25_and_75)

[(98, 'student8'), (93, 'student11'), (80, 'student10'), (78, 'student2'), (48, 'student5')]
[(12, 'student3'), (14, 'student4'), (35, 'student9'), (43, 'student6'), (45, 'student1')]
[(35, 'student9'), (43, 'student6'), (45, 'student1'), (47, 'student7'), (48, 'student5'), (78, 'student2'), (80, 'student10')]


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [38]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    # write your code here
    distnace_list=[]
    for point in S:
      numerator = (point[0]*P[0]) + (point[1]*P[1])
      denominator = math.sqrt((math.pow(point[0],2) + math.pow(point[1],2)) * (math.pow(P[0],2) + math.pow(P[1],2)))
      dist = math.acos(numerator/denominator)
      distnace_list.append((round(dist,4),point))
      sorted_list = sorted(distnace_list)
    return sorted_list[0:5] # its list of tuples

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1),(6,0),(1,-1)]
P= (3,-4)
points = closest_points_to_p(S, P)
print(points) #print the returned values

[(0.0651, (6, -7)), (0.1419, (1, -1)), (0.9273, (6, 0)), (1.2021, (-5, -8)), (1.4289, (-1, -1))]


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [ ]:
import math
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def i_am_the_one(red,blue,line):
    # your code
    red_distance_set = set()
    blue_distance_set = set()
    for point in red:
      red_line = line.replace('x','*'+str(point[0]))
      red_line = red_line.replace('y','*'+str(point[1]))      
      distance = eval(red_line)
      #print('Red diatnce is {}'.format(distance))
      if distance > 0:
        red_distance_set.add('P')
      else:
        red_distance_set.add('N')

    for point in blue:
      blue_line = line.replace('x','*'+str(point[0]))
      blue_line = blue_line.replace('y','*'+str(point[1]))      
      distance = eval(blue_line)
      #print('Blue diatnce is {}'.format(distance))
      if distance > 0:
        blue_distance_set.add('P')
      else:
        blue_distance_set.add('N')
      
    if (len(red_distance_set) == 1 and len(blue_distance_set) ==1 and red_distance_set != blue_distance_set):
      return 'Yes'
    else:
      return 'No'

    
    return point #yes/no

Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
#Lines=["1x+0y-3"]

for i in Lines:
    yes_or_no = i_am_the_one(Red, Blue, i)
    print(yes_or_no) # the returned value

Yes
No
No
Yes


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [ ]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

import math
# you can free to change all these codes/structure
def curve_smoothing(s):
    # your code
    str_arr = s.split(",")
    array_len = len(str_arr)
    strt_index = 0
    
    for i in range(len(str_arr)):
      if str_arr[i] != '_':
        non_zero_index = i
        temp_val = str_arr[i]
        if strt_index == 0 and str_arr[strt_index] == '_':   
          temp_val = int(int(str_arr[i])/(i+1))
        else:
          if strt_index != i:
            temp_val =  int((int(str_arr[strt_index])+int(str_arr[i]))/((i - strt_index) + 1))
        for j in range(strt_index,i+1):
            str_arr[j] = temp_val        
        strt_index = i
      else:
        strt_index = min(strt_index,i)
        if i == (array_len - 1):
          temp_val = int(int(str_arr[strt_index])/(array_len - strt_index))
          for k in range(strt_index,array_len):
            str_arr[k] = temp_val
    

    return str_arr #list of values

s =  "_,_,30,_,_,_,50,_,_"
#s =  "_,_,30"
smoothed_values = curve_smoothing(s)
print(smoothed_values)


[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [37]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
#from collections import Counter


# you can free to change all these codes/structure
def construct_dictionaries(A):
  list_dict = {}
  F_dict = {}
  S_dict = {}
  for item in A:
    if tuple(item) in list_dict:      
      list_dict[tuple(item)] += 1
    else:
      list_dict[tuple(item)] = 1
    for sub_list_item in item:
      if sub_list_item[0] == 'F':
          if sub_list_item in F_dict:
              F_dict[sub_list_item] += 1
          else:
            F_dict[sub_list_item] = 1
      else:
          if sub_list_item in S_dict:
              S_dict[sub_list_item] += 1
          else:
            S_dict[sub_list_item] = 1
  return list_dict,F_dict,S_dict

def compute_conditional_probabilites(A):
  list_dict,F_dict,S_dict = construct_dictionaries(A)
  str_format = 'P(F={}|S=={})={}'
  result_list = []
  
  for f_val in F_dict:
    for s_val in S_dict:
      prob_val = 0
      if tuple([f_val,s_val]) in list_dict:
        prob_val = str(list_dict[tuple([f_val,s_val])])+'/'+str(S_dict[s_val])
      else:
        prob_val  = '0/'+str(S_dict[s_val])
      result_list.append(str_format.format(f_val,s_val,prob_val))
  return result_list

    # your code
    # print the output as per the instructions

A = [['F1','S1'],['F2','S2'],['F3','S3'],['F1','S2'],['F2','S3'],['F3','S2'],['F2','S1'],['F4','S1'],['F4','S3'],['F5','S1']]
result = compute_conditional_probabilites(A)
for res in result:
  print(res)

P(F=F1|S==S1)=1/4
P(F=F1|S==S2)=1/3
P(F=F1|S==S3)=0/3
P(F=F2|S==S1)=1/4
P(F=F2|S==S2)=1/3
P(F=F2|S==S3)=1/3
P(F=F3|S==S1)=0/4
P(F=F3|S==S2)=1/3
P(F=F3|S==S3)=1/3
P(F=F4|S==S1)=1/4
P(F=F4|S==S2)=0/3
P(F=F4|S==S3)=1/3
P(F=F5|S==S1)=1/4
P(F=F5|S==S2)=0/3
P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [7]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings

# you can free to change all these codes/structure
def string_features(S1, S2):
    # your code
    s1_set = set(S1.split())
    s2_set = set(S2.split())
    common_count = len(s1_set & s2_set)
    S1_NOT_S2 = [i for i in s1_set - s2_set]
    S2_NOT_S1 = [i for i in s2_set - s1_set]
    return common_count, S1_NOT_S2,S2_NOT_S1

S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
a,b,c = string_features(S1, S2)
print(a)
print(b)
print(c)

7
['F', '5', 'first']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [35]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings
import math

# you can free to change all these codes/structure
def compute_log_loss(A):
    len_A = len(A)
    x = 0
    for item in A:
      x += ( ( item[0]*math.log10(item[1]) ) + ( (1-item[0])*math.log10(1-item[1])) ) 
    return ((-1/len_A)*x)

A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(loss)

0.42430993457031635
